Update build-kernel-fix.yml

diff --git a/.github/workflows/build-kernel-fix.yml b/.github/workflows/build-kernel-fix.yml
--- a/.github/workflows/build-kernel-fix.yml
+++ b/.github/workflows/build-kernel-fix.yml
@@ -27,29 +27,24 @@ jobs:
 
     - name: Setup KernelSU-Next
       run: |
-        # Clean up any old KernelSU setup to prevent conflicts
-		[ -L "drivers/kernelsu" ] && rm "drivers/kernelsu"
-		grep -q "kernelsu" "./drivers/Makefile" && sed -i '/kernelsu/d' "./drivers/Makefile"
-		grep -q "source \"drivers/kernelsu/Kconfig\"" "./drivers/Kconfig" && sed -i '/drivers\/kernelsu\/Kconfig/d' "./drivers/Kconfig"
-		if [ -d "./KernelSU*" ]; then
-		  rm -rf "./KernelSU*"
-		fi
+        # Remove existing KernelSU setup
+        rm -rf KernelSU-Next KernelSU drivers/kernelsu
+        # Install latest KernelSU-Next 1.0.9
+        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s v1.0.9
+        # Verify installation
+        ls -la drivers/kernelsu/
+        ls -la drivers/kernelsu/Kconfig || echo "Kconfig not found"
 
-		# Add KernelSU repository as a submodule
-		git submodule add --force -b next https://github.com/KernelSU-Next/KernelSU-Next.git ./KernelSU
-
-		# Apply KernelSU patches to kernel source
-		ln -sf ../KernelSU/kernel ./drivers/kernelsu
-		grep -q "kernelsu" "./drivers/Makefile" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> "./drivers/Makefile"
-		grep -q "source \"drivers/kernelsu/Kconfig\"" "./drivers/Kconfig" || sed -i "/endmenu/i\source \"drivers/kernelsu/Kconfig\"" "./drivers/Kconfig"
-
-		# Apply manual scope-minimized hooks with coccinelle
-		git clone --depth=1 https://github.com/devnoname120/kernelsu-coccinelle.git
-		for p in fs drivers/input drivers/tty arch/arm/kernel; do spatch --sp-file ./kernelsu-coccinelle/scope-minimized-hooks/kernelsu-scope-minimized.cocci --in-place --linux-spacing "$p"; done
-
-		# Cleanup temporary files and revert potentially conflicting Android files
-		rm -rf ./kernelsu-coccinelle/
-		rm -rf ./android/abi_gki_protected_exports*
+    - name: Patch KernelSU manual scope-minimized hooks into the kernel source
+      run: |
+          # Clone the repository which contains the patch
+          git clone --depth=1 https://github.com/devnoname120/kernelsu-coccinelle.git
+          # Patch the kernel source with scope-minimized hooks
+          for p in fs drivers/input drivers/tty arch/arm/kernel; do spatch --sp-file ./kernelsu-coccinelle/scope-minimized-hooks/kernelsu-scope-minimized.cocci --in-place --linux-spacing "$p"; done
+          # Cleanup
+          rm -rf ./kernelsu-coccinelle/
+          # Delete files that may conflict with kernel functionality
+          rm -rf ./android/abi_gki_protected_exports*
 
     - name: Cache proton-clang
       uses: actions/cache@v3
